#!/usr/bin/env python

import os
import sys
from optparse import OptionParser
import logging
import tornado.ioloop

import slickbird


def _logging_verbose(option, opt, value, parser):
    logging.getLogger().setLevel(logging.INFO)


def main():
    prog = os.path.basename(sys.argv[0])
    logging.basicConfig(format=prog + ': %(message)s')
    parser = OptionParser(usage="Usage: %prog <file>", description=__doc__)
    parser.add_option('-v', '--verbose',
                      action="callback", callback=_logging_verbose,
                      help='Be more verbose.')
    (cfg, args) = parser.parse_args()
    if len(args) != 0:
        parser.error('Invalid arguments.')
    app = slickbird.make_app()
    app.listen(8888)
    tornado.ioloop.IOLoop.current().start()


if __name__ == "__main__":
    main()
