#!/usr/bin/env python

import sys
import os
import logging
import tornado
from tornado.options import parse_command_line, parse_config_file
from tornado.options import options, print_help

import slickbird.scrapper
from slickbird import orm


def _log():
    if not _log.logger:
        _log.logger = logging.getLogger(__name__)
    return _log.logger
_log.logger = None


@tornado.gen.coroutine
def scrap(session, home):
    sc = slickbird.scrapper.Scrapper(session, home)
    yield sc.scrap_missing()
    tornado.ioloop.IOLoop.current().stop()


def main():
    defcfg = 'slickbird.cfg'
    parse_command_line()
    if options.config:
        parse_config_file(options.config)
    elif os.path.exists(defcfg):
        parse_config_file(defcfg)
    parse_command_line()  # override config file
    args = []
    for a in sys.argv[1:]:
        if a.startswith('--'):
            continue
        args.append(a)
    if len(args) > 0:
        print('Usage: {}'.format(sys.argv[0]))
        print_help()
        sys.exit(1)
    session = orm.make_session(options.database)()
    io_loop = tornado.ioloop.IOLoop.current()
    tornado.ioloop.IOLoop.current().spawn_callback(
        scrap, session, options.home)
    io_loop.start()


if __name__ == "__main__":
    main()
