#!/usr/bin/env python

import os
import sys
import logging
from optparse import OptionParser
import urlparse
import requests


def _log():
    if not _log.logger:
        _log.logger = logging.getLogger(__name__)
    return _log.logger
_log.logger = None


def _logging_verbose(option, opt, value, parser):
    logging.getLogger().setLevel(logging.INFO)


def main():
    prog = os.path.basename(sys.argv[0])
    logging.basicConfig(format=prog + ': %(message)s')
    parser = OptionParser(
        usage="Usage: %prog <collections...>", description=__doc__)
    parser.add_option('-v', '--verbose',
                      action="callback", callback=_logging_verbose,
                      help='Be more verbose.')
    parser.add_option('-u', '--url',
                      type='string', default='http://127.0.0.1:8888',
                      help='Base URL of server; default http://127.0.0.1:8888')
    (cfg, args) = parser.parse_args()
    if len(args) == 0:
        parser.error('Invalid arguments.')
    data = {'name': ''}
    for filename in args:
        files = {'datfile': open(filename)}
        requests.post(
            urlparse.urljoin(cfg.url, 'add'),
            data=data, files=files)


if __name__ == "__main__":
    main()
